apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "testchart.fullname" . }}-pre-install-hook"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: pre-install
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo 'Running pre-install hook' && sleep 5"]
  restartPolicy: OnFailure