[tools]
# 以下のいずれかの形式で指定可能：

# 1. チルダ(~) - パッチバージョンの自動更新のみ
# node = "~20.11.0"  # 20.11.0, 20.11.1, 20.11.2... (20.12.0は含まない)

# 2. キャレット(^) - マイナー・パッチバージョンの自動更新
# node = "^20.11.0"  # 20.11.0, 20.12.0, 20.13.0... (21.0.0は含まない)

# 3. 具体的なバージョン指定
# node = "20.11.1"   # 固定バージョン

# 4. メジャーバージョンのみ（現在の指定方法）
# node = "20"        # 20.x.xの最新版

# 推奨: LTS版でマイナー・パッチの自動更新を許可
node = "^20.11.0"
